# Configure Netlify to serve particular headers for certain routes
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin"
    Strict-Transport-Security = "max-age=2592000; includeSubDomains"
    X-Content-Type = "nosniff"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    # Multi-key header rules are expressed with multi-line strings.
    Content-Security-Policy = '''
    default-src 'none';
    font-src 'self';
    img-src 'self';
    style-src 'self' 'unsafe-inline';
    '''
